### PR TITLE
German translation

### PR DESCRIPTION
**Pull request by Unruly-MAC**
This includes an added readme file translated from english to german

### CODE REVIEW

**Comment by something-cool** [comment]
The edited folder/file contained Dutch text (from The Netherlands; du-NL).

His German translation should indeed have its own de-DE folder.

**Comment by AllThingsSmitty** [comment]
@Unruly-MAC so is this a Dutch translation or a German translation? de-DE or du-NL?

**Comment by pepijngieles** [comment]
This was a Dutch translation but the commit shows @Unruly-MAC translated it to German. The land code is still Dutch so should be adjusted to de-DE.

**Comment by Unruly-MAC** [comment]
It is Dutch translated and should be de-De but my github was giving issues so I emailed the file to my friend to use my account and pull requested it

**Comment by AllThingsSmitty** [comment]
@Unruly-MAC can you update your PR so the translation folder is de-DE? Thanks.

**Pull request merged**
