### PR TITLE
Hello I made the translation to Greek 

### PR DESCRIPTION
**Pull request by manolasn**
That's my first contribution 😄

### CODE REVIEW

**Comment by manolasn** [comment]
It's for a project of my college,hope this contribution helps you and also I hope you can pull my file until the 9th of February because I have a deadline 😅

**Comment by AllThingsSmitty** [comment]
Doing a quick review, looks like not all the links in the table of contents go to the sections below. Can you correct that? Double-check they all work. Also, no need to add a link to contribution guidelines. That's just on the English version only.

**Comment by manolasn** [comment]
Of course I'm checking it right now.

**Comment by manolasn** [comment]
I think now it's okay i fixed the problems .

**Comment by manolasn** [comment]
Hello have a nice week, have you checked my links again, I think now the coding it's correct, right?

**Comment by AllThingsSmitty** [comment]
@manolasn hoping to review later today.

**Comment by manolasn** [comment]
Okay I will be waiting.

**Comment by AllThingsSmitty** [comment]
Looks like the link to "Translations" (Μεταφράσεις) is still wrong. It needs to go to https://github.com/AllThingsSmitty/css-protips/blob/b8a3f3bf09b83d2bac4f04be7f9487b1db681d5c/CONTRIBUTING.md.

**Comment by manolasn** [comment]
Sorry about that I forgot to check it, it's okay now.

**Pull request merged**
