### PR TITLE
:not() alternative for menu siblings elements

### PR DESCRIPTION
**Pull request by stphane**
Even supported under IE8 (You are right.. who cares now ! Almost nobody .. almost.)

### CODE REVIEW

**Comment by AllThingsSmitty** [comment]
@stphane thanks for the suggestion. I'm trying to keep these tips specific to more current browsers: https://github.com/AllThingsSmitty/css-protips#support

**Comment by robsonsobral** [comment]
Hi! Since the suggestion isn't specific for IE8, I think it doesn't hurt the list of supported browsers. And to know alternative ways of do the same thing can be useful to find solutions for new problems. The whole point of this list is to be help, right?

Maybe to have two sections:

- "select all siblings but the first";
- "select all siblings but the last".

Thanks for the list anyway, @AllThingsSmitty !

**Comment by AllThingsSmitty** [comment]
@robsonsobral  @stphane I'll take a look at it. Thanks.

**Comment by stphane** [comment]
My proposal is just a valid css alternative. I could have left the optional description empty in the pull request. The IE fact is like icing on the cake I would say.

**Comment by AllThingsSmitty** [comment]
@stphane I see that. I agree this could be a useful alternative.

**Comment by AllThingsSmitty** [comment]
Added (and slightly tweaked) with https://github.com/AllThingsSmitty/css-protips/commit/43e82e58e7649c0d233250fe04b59f26fd2918ba.

**Pull request closed without merging**
