### PR TITLE
pro tip to center any absolute div within a relative div

### PR DESCRIPTION
**Pull request by ktkaushik**
Let me know if this is okay please. I have created a small [codepen for demonstration](http://codepen.io/ktkaushik/pen/epRMBG) as well.

### CODE REVIEW

**Comment by AllThingsSmitty** [comment]
@ktkaushik thanks for the suggestion. I'm not certain what the use case is for this kind of tip. It seems more like an edge case on not something that devs would get much value from using regularly.

**Comment by wmertens** [comment]
It is the best way to center a div if you know its size and you don't have flexbox available. It doesn't work if the centered div is not a fixed size.

**Comment by vikrantnegi** [comment]
Yes CSS-tricks have all the [centering techniques](https://css-tricks.com/centering-css-complete-guide/) you need to know.

**Comment by AllThingsSmitty** [comment]
Given that the CSS-Tricks post has a lot of good suggestions I've simply added a link to it under the tip for vertically-centering.

**Pull request closed without merging**
