### PR TITLE
Updated with demo

### PR DESCRIPTION
**Pull request by shanksrepo**
More precise code with [demo](http://codepen.io/shanksrepo/pen/OygmNB)

### CODE REVIEW

**Comment by AllThingsSmitty** [comment]
@shanksrepo thanks, the demos helps me understand what you're doing. I slimmed down the code some to see more what you're getting at:

```html
<div class="container">
  <div class="content"></div>
</div>
```
```css
.container {
  width: 20%;
}
.container .content {
  width: 100%;
  height: 0;
  position: relative;
}
.container .content:before {
  padding-top: 100%;
  width: 100%;
  background: #009530;
  content: "";
  position: absolute;
  top: 0;
}
```

The only real question I have is whether aspect ratio is something that devs do a lot in CSS. It's a nice trick, though.

**Comment by robsonsobral** [comment]
Shouldn't has a note on the `padding-top` about the ratio?

- `100%` is 1:1;
- 16:9 is `56.25%`: 9 / 16 * 100.

**Comment by shanksrepo** [comment]
@AllThingsSmitty Well I used this trick in many of my recent projects. And yes its very specific stuff, however whoever is working on responsive grid will be usefull to them.
And we really don't know what will make whome & when happy :)

Thanks for sharing your views.

**Comment by shanksrepo** [comment]
@robsonsobral You are correct your note will help more.

Thanks for sharing your views

**Comment by AllThingsSmitty** [comment]
Addressed with https://github.com/AllThingsSmitty/css-protips/commit/d28d5dd9baeca0cbc1745526b6398068d594a738 which references [this CSS-Tricks post](https://css-tricks.com/centering-css-complete-guide/) for more complete centering examples.

**Pull request closed without merging**
