### PR TITLE
Flex align

### PR DESCRIPTION
**Pull request by sagban**
Align the flex items at the centre of the container.

`div {
 display: flex; justify-content: center; 
}`
This is the quick and easy way to get your divs aligned.

### CODE REVIEW

**Comment by sagban** [comment]
Yes It does work with IE11.
flex

**Comment by sagban** [comment]
Do I have to make any corrections here?

**Comment by AllThingsSmitty** [comment]
I'm currently reviewing this tip.

**Comment by AllThingsSmitty** [comment]
There's already a section on vertical alignment with a link to a CSS Tricks post on vertical/horizontal aligning anything.

**Pull request closed without merging**
